### ISSUE TITLE
RFE: Mark all as read

### ISSUE THREAD

**Issue by inducer** [pfleidi/yaxim#104]
The roster (helpfully) shows contacts for whom you have unread messages, and the chat history highlights the unread ones with a fade grey->white. Those are great features. Sometimes it happens that I've already seen all those messages on my PC, and currently I have to select the contact and scroll up (sometimes through pages of conversation) just to return the contact to "read" state. It'd be great if there was a more efficient way to say "I've read all these messages."

Thanks for your work on yaxim!

**Comment by ge0rg** [comment]
There is now a "mark as read" option on contacts and a "mark all as read" in the main menu. [Beta APK](https://yaxim.org/archive/builds/yaxim-gl-2016-12-19.apk). This will also become part of 0.9 soon.
