### ISSUE TITLE
Not enough notifications in carbon copy chat

### ISSUE THREAD

**Issue by inducer** [pfleidi/yaxim#114]
You mentioned this in issue #104, but I finally understood what you meant, and I disagree with it. :-1: In a carbon copy chat, I would prefer if no notifications were only silenced for outgoing messages, but not for incoming ones. IIUC, at present all notifications after the first one are silenced.

The scenario that makes this awkward is if you've somehow missed the first notification, you do not get a chance to recover, because no more notifications are played. I'll agree that this may be a matter of taste, but the number of messages I've missed this way since I've upgraded is staggering. :/

**Comment by ge0rg** [comment]
The latest [nightly APK](https://yaxim.org/archive/builds/yaxim-gl-2018-04-01.apk) (also on [Google Play beta channel](https://play.google.com/apps/testing/org.yaxim.androidclient)) now has a vastly different notification sound logic.

* There is no more difference between carbons and "real" messages
* yaxim will make all notifications silent (no ringtone/vibration), if the yaxim user was active from a different device in the last 2:24 minutes (the value is "stolen" from Conversations' "short grace period" setting)
* yaxim will clear the notifiication for a given contact (and mark that as read) if you respond from a different client

On the TODO:
* remember which notifications were silent and play back their sound if the user doesn't react from the other client.
