### ISSUE TITLE
Add support for smileys

### ISSUE THREAD

**Issue by allo-** [pfleidi/yaxim#116]
This is a killerfeature to get newbies to use XMPP. At least the standard smileys should be supported, bonus points if you add more than WhatsApp ;).

**Comment by ge0rg** [comment]
Google's keyboard (and many other alternative keyboard apps) now provide their own tab with a huge collection of Unicode Emoji. I'm closing this as the keyboard is in a much better position to implement smileys, and as I'm already actively using that feature.
