### ISSUE TITLE
Add @server.tld from connected XMPP server for new contacts automatically

### ISSUE THREAD

**Issue by kriztan** [pfleidi/yaxim#136]
For me it would be nice, if yaxim could add @server.tld from connected XMPP server automatically on adding a new contact. Is it possible to implement in future?
Thanks

**Comment by ge0rg** [comment]
This has been fixed in cd9965e9aeaa52ab1748a140820fe9eadb4028a9 and will become part of the 0.9 release. [Beta APK](https://yaxim.org/archive/builds/yaxim-gl-2016-12-19.apk).
