### ISSUE TITLE
Feature: Add support for google:queue

### ISSUE THREAD

**Issue by iNPUTmice** [pfleidi/yaxim#143]
google:queue (not a proper XEP but described here: http://mail.jabber.org/pipermail/summit/2010-February/000528.html) will prevent unnecessary wake ups while in background. It's not as complicated as SIFT for example. It simply gets the job done. It is easy to understand. Adding support on server side shouldn't be more than a couple of lines. (With existing stream management code)

I'm cross posting this issue to a couple of projects. Maybe we can implement this at the same time.

**Comment by ge0rg** [comment]
This is now part of the [0.9 beta](https://play.google.com/apps/testing/org.yaxim.androidclient) and will be published soon[tm].
