### ISSUE TITLE
Empty conversations should open with keyboard expanded

### ISSUE THREAD

**Issue by da2x** [pfleidi/yaxim#158]
1. Click on a contact for which there is no message log

Expected: Since there are no messages to display, the keyboard should be visible without anymore user interaction required. Allowing the user to start their conversation faster. (Reference how most SMS apps works.)

Actual: “Enter message” is shown at the bottom of the screen. Insertion cursor us blinking, showing that the field has focus. User must still click on it to bring up a keyboard.

**Comment by ge0rg** [comment]
This is now part of the [0.9 beta](https://play.google.com/apps/testing/org.yaxim.androidclient) and will be published soon[tm].
