### ISSUE TITLE
feature request: Please add intent interface to support sending XMPP messages without user interaction

### ISSUE THREAD

**Issue by christf** [pfleidi/yaxim#172]
- the message should be sent to a contact that is passed via argument.
- if yaxim is offline, the message should be queued and sent asap
- a security token should be used

This will allow yaxim to be used from llama / tasker

**Comment by ge0rg** [comment]
With yaxim you can handle [XMPP message URIs](http://xmpp.org/extensions/xep-0147.html) like this one:

    xmpp:georg@yax.im?message;body=hello+there

It will open a chat window and require manually pressing 'OK'. Everything beyond that is out of focus for the app, sorry.
