### ISSUE TITLE
yaxim service restarts when switching wifi on or off

### ISSUE THREAD

**Issue by groupnetteam** [pfleidi/yaxim#178]
when you are in app and you switch wifi off and then you press home button then you close app adn after that switching wifi on it will restart service but i have checked all app (securechat,telegram,viber,whatsapp) and none of them has this problem.

the main issue is that every time you are not in app and turning wifi or data on or off will cause stream handler not work correctly and messages get lost.

if you want test that please follow this procedure
1-open yaxim and log into one account
2-when you are online turn wifi off
3-press home button and close app
4-send some messages to the user that you have had logged into it.
5-turn wifi or data on (if you see the online offline indicator of yaxim in notification bar you can see    that after turning wifi on the service will get restarted)
6-open app and wait to connect to server

then you wont get messages that are sent to this user because after switching wifi the service gets restarted and resume wont happen

best solution is not letting yaxim service restarts after switching wifi or data on or off

if you cant understand problem please add me on skype to show you the problem in a video call

my skype is :groupnetteam

**Comment by ge0rg** [comment]
Please follow up in #179
