### ISSUE TITLE
stream handler will not work after service gest killed

### ISSUE THREAD

**Issue by groupnetteam** [pfleidi/yaxim#179]
Hello Ge0rG. there is a problem with xep-198 in yaxim. that is when service gets killed the messages that had not got the stanza will be lost.let me explain it better. consider this situation you turn wifi suddenly off,server think user is online and the tcp connection will be open and then another client send messages to this user,if you kill service and open app again the message will be lost because i think the resume wont be done.i think the reason is after getting service killed the value of parameters that are user for stream handler will be set to default value
( these parameters
```java
private static final String URN_SM_2 = "urn:xmpp:sm:2";

private static final int MAX_OUTGOING_QUEUE_SIZE = 200;

private static final int REQUEST_ACK_AFTER_STANZAS = 10;

private ExtXMPPConnection mConnection;

private boolean isSmAvailable = false;

private boolean isSmEnabled = false;

private boolean isOutgoingSmEnabled = false;

private boolean debugStanzas = false;

private long previousIncomingStanzaCount = 0;

private String sessionId;

private long incomingStanzaCount = 0;

private long outgoingStanzaCount = 0;

private long outgoingStanzasSinceAckRequest = 0;
)
```
and after that resume wont be done

actually what is needed to be done is that we should find out which parameters are used to let user resume stream handler after restarting service 

what i have found after some analyse is that when service restarts SM-ID or Sessionid wont be same as previous session (after getting service killed the session is will change and one of condition for resuming session is ,previos sessionid needs to be same as new session id )

so what we need is that we shouldnt let parameters that are used for resuming stanza changes after restarting service and i think it is just sessionid or SM-ID

**Comment by ge0rg** [comment]
Sorry, I'm not doing support over skype, as I lack the time.

Do you have the "yaxim icon" in the notification bar? If not, you should enable it to prevent out-of-memory kills.
