### ISSUE TITLE
File transfer using In-band bytestreams (IBB) method

### ISSUE THREAD

**Issue by nhede** [pfleidi/yaxim#184]
The In-band bytestreams (IBB) method (XEP-0047) (supported by pidgin and gajim messengers),
makes file transfers over the already existing secure/encrypted xmpp connection posible. 
Ok this is no end to end encryption, but still a lot better than XEP-0096 (SI File Transfer) using proxy.
Pidgin and gajim using this as fallback solution if the proxy does not work.

With gajim you can disable file transfer proxy in de account config, and it falls back to IBB.
With Pidgin you have to put a dummy url in the file transfer proxy field.

Maybe the IBB method is an acceptable solution for file transfer.

**Comment by ge0rg** [comment]
I agree, and I have considered this seriously. Unfortunately, this is going to add a hell of a load (both network and CPU) to the XMPP server(s) between the users, as you are literally flooding the server with stanzas.

My biggest fear (as a client developer) is that servers will deploy stanza throttling / dropping, effectively breaking your complete XMPP experience.

There were some awesome ideas to clone the WebRTC end-to-end encrypted connections to transfer media (maybe also files), using SCTP-DTLS. This is the direction I want to go forward. If this fails to lift off, I'd rather see the [CurveCP](http://curvecp.org/) protocol over UDP/SCTP for end-to-end security.
