### ISSUE TITLE
option to register account

### ISSUE THREAD

**Issue by mvhulten** [pfleidi/yaxim#192]
It would be nice to have the option in yaxim to register an account. I cannot find this option (when changing account details).

Interestingly, https://yaxim.org/yax.im/ suggests that this should work.

**Comment by ge0rg** [comment]
It works, but it is kind of hidden: you need to reset the app to defaults (or at least remove the JID from the preferences) and the first startup dialog will be shown.

**Comment by ge0rg** [comment]
There is now an improved setup dialog in the yaxim 0.9 beta, that will not endlessly loop if you try to register an account. However, registration is only possible on a fresh install.
