### ISSUE TITLE
server xep 0313 MAM

### ISSUE THREAD

**Issue by solarnoid** [pfleidi/yaxim#194]
Please add server feature to better serve secure clients like conversations.  Please update yaxim client also

**Comment by solarnoid** [comment]
.

**Comment by ge0rg** [comment]
For the server: this feature is not yet marked as stable in prosody. Also, I consider storing a large backlog for all users a privacy issue.

For yaxim: somebody needs to implement it.

**Comment by ge0rg** [comment]
yax.im now has MAM enabled.
