### ISSUE TITLE
server xep 0352 Client State Indication

### ISSUE THREAD

**Issue by solarnoid** [pfleidi/yaxim#195]
Please add server feature to better serve secure clients like conversations.  Please update yaxim client also

**Comment by solarnoid** [comment]
.

**Comment by ge0rg** [comment]
Are you talking about yax.im the server or yaxim the client?

For the server: the prosody code for CSI still has some funny bugs in combination with XEP-0198, which is much more important to mobile clients

yaxim the client supports google:queue, which can be enabled in prosody with mod_csi_compat. I will switch that to proper CSI when the time permits.

**Comment by ge0rg** [comment]
mod_csi and it's siblings are enabled on yax.im for a while already. Closing.
