### ISSUE TITLE
0.9 submodules point to non existent commits

### ISSUE THREAD

**Issue by krt16s** [pfleidi/yaxim#198]
````
==== detail begin ====
Submodule 'ActionBarSherlock' (git://github.com/JakeWharton/ActionBarSherlock.git) registered for path 'ActionBarSherlock'
Submodule 'MemorizingTrustManager' (git://github.com/ge0rg/MemorizingTrustManager.git) registered for path 'MemorizingTrustManager'
Cloning into 'ActionBarSherlock'...
fatal: reference is not a tree: 5f7f046756c1ffb0e782dde82e6f75d9c433ba38
Cloning into 'MemorizingTrustManager'...
Submodule path 'MemorizingTrustManager': checked out '587f2d3e2b33583e4b50f86b5561b1bd94f6b571'
Unable to checkout '5f7f046756c1ffb0e782dde82e6f75d9c433ba38' in submodule path 'ActionBarSherlock
````

**Comment by ge0rg** [comment]
Whoops, consider me guilty. I've had to replace the v4 compat jar in ABS to support android auto. I'll clean up the mess early next week and let you know.

**Comment by ge0rg** [comment]
@krt16s could you test if the current master tree compiles (with `commit=69224b521e89e1934d7817ca5bd3b85818fd6800`)? I'm preparing a 0.9.1 release, and I'd like to get it right this time so that fdroid and google play become consistent again.

**Comment by krt16s** [comment]
Builds for me with proguard disabled. Need to look into the issue, also havent tested the apk, which I hope to  do tomorrow.

**Comment by ge0rg** [comment]
Thanks very much. It looks like the no-proguard build is adding around ~500KB (going up to 2.2MB), so this shouldn't be critical. A brief test of (my own) no-proguard `ant debug` build looks like it's working as well.

**Comment by ge0rg** [comment]
Did you have a chance to test-run the code? I'm almost ready to push out 0.9.1 :)

I also did some work to make the code base compile with gradle, but it's not 100% there yet and not very well tested.
