### ISSUE TITLE
No media, images sharing 

### ISSUE THREAD

**Issue by kshitijvyas1985** [pfleidi/yaxim#202]
Is there a functionality to add media like video or images.
I havn't find any class doing so. If I can add smack-android lib. to make connection. But that is generating error in smackable interface.

**Comment by ge0rg** [comment]
yaxim can send images and files via HTTP-Upload now. Inline previews are still work-in-progress.

Available in nightly builds and Google Play beta:
https://play.google.com/apps/testing/org.yaxim.androidclient
