### ISSUE TITLE
Disconnection reason not (always?) shown

### ISSUE THREAD

**Issue by Zash** [pfleidi/yaxim#205]
While testing, I deleted the account I had Yaxim connected to, and all it said was "Disconnected". Prosody, when deleting an account, closes any open sessions of that account with the condition [`not-authorized`](https://xmpp.org/rfcs/rfc6120.html#streams-error-conditions-not-authorized) and a textual message along the lines of `"Account deleted"`.
Showing the textual message would be nice.

**Comment by ge0rg** [comment]
Interesting, I just recently deleted an account that still was logged in and got the correct message displayed. It's possible that yaxim's internal error message is updated when your WiFi / 3G connection changes or other related events occur. Maybe it's also due to an automatic reconnect from yaxim.

**Comment by Zash** [comment]
yaxim 0.9.2 FWIW, I suppose I should test again to be sure

**Comment by Zash** [comment]
Hm, hard to tell, but it's possible that something flashes by and then gets replaced by "Disconnected".

**Comment by Zash** [comment]
In debug logs it looks like it says "Connecting to server?" and then the connection is closed.

**Comment by ge0rg** [comment]
Yes, that sounds like yaxim. There is no easy way to distinguish permanent errors (account deleted) from transient networks (server shutdown, network outage), so yaxim will auto-reconnect after 5 seconds or on the next network change. It should tell you that username/password don't match on next connect, though.

**Comment by ge0rg** [comment]
Okay, I just tested it. When you delete the account on the server, yaxim will display, for 5 seconds, this message:

> stream:error (not-authorized) text: Account deleted

And then it will happily go on reconnecting to the server, which obviously leads to

> SASL authentication failed using mechanism PLAIN

The current project infrastructure doesn't allow to improve that in a relevant way, sorry.
