### ISSUE TITLE
go away when screen is off / go DnD when phone is silent

### ISSUE THREAD

**Issue by one-dash** [pfleidi/yaxim#21]
It would be very convenient to client set status to 'away' when device's screen goes off. The status message could be configurable by user. That's a standard feature for many smartphone IM clients

**Comment by ge0rg** [comment]
For now, I have implemented "DND when silent" in 202197bef5ec3e7c116e2c27da8dcfa8671eee63 and a config option to disable this in 856c247a75be4b98871e8df38e823d4d9bc07b30. This will be part of the next release. [Beta APK](https://yaxim.org/archive/builds/yaxim-gl-2016-12-19.apk).

For now I'm refraining from implementing auto-away (it would have to be implemented based on user (in)activity and might leak too much information about the user).
