### ISSUE TITLE
your application is not working configured android Studio.

### ISSUE THREAD

**Issue by ddpatel2606** [pfleidi/yaxim#218]
I have try hard to implement chat app in android studio using your code but not able to do that.

I am not able to configure ParcelablePresence.aidl file it gives always error.

Kindly, Suggest some help

Thanks

**Comment by ge0rg** [comment]
Please provide a copy&paste / screenshot of the exact error you have.

The build process requires an old AndroidStudio / gradle 3.3, and I haven't upgraded it yet.

**Comment by ddpatel2606** [comment]
I am using Android Studio 3.1.3
Build #AI-173.4819257, built on June 4, 2018
JRE: 1.8.0_152-release-1024-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-45-generic

**Comment by ddpatel2606** [comment]
I am using

Android Studio 3.1.3
Gradle : 4.4 ,  Android plugin version : 3.1.3

![screenshot from 2018-07-19 16-49-45](https://user-images.githubusercontent.com/4408862/42939648-26e8e63e-8b74-11e8-82fc-c3cfc7553e85.png)
 
Not able to configure ParcelablePresence type cast

**Comment by ge0rg** [comment]
You are trying to import the wrong class. Correct is `org.yaxim.androidclient.service.ParcelablePresence`.

**Comment by ddpatel2606** [comment]
yes I have resolved issue,

thanks for your support.
