### ISSUE TITLE
Предпросмотр картинок

### ISSUE THREAD

**Issue by ghost** [pfleidi/yaxim#219]
Сделайте предпросмотр присылаемых картинок в клиенте.

https://github.com/pfleidi/yaxim/pull/208

https://4pda.ru/forum/index.php?s=&showtopic=227119&view=findpost&p=71474212

**Comment by ge0rg** [comment]
Fixed in 0.9.3 / 2659e3e4870363c50f78783cfaeed09c5242bd55.
