### ISSUE TITLE
feature request: support MUC

### ISSUE THREAD

**Issue by one-dash** [pfleidi/yaxim#29]
That would be a killer feature for yaxim :-)

**Comment by the-solipsist** [comment]
Any progress on this, @ge0rg?

**Comment by ge0rg** [comment]
I'm preparing a MUC-enabled yaxim release finally, 0.9.0. [Beta APK](https://yaxim.org/archive/builds/yaxim-gl-2016-12-19.apk).

[Beta channel on Google Play](https://play.google.com/apps/testing/org.yaxim.androidclient).

Please test and let me know :)

**Comment by ge0rg** [comment]
Finally: yaxim 0.9 is there!
