### ISSUE TITLE
feature request: support XEP-0146(client remote control)

### ISSUE THREAD

**Issue by one-dash** [pfleidi/yaxim#36]
XEP-0146 is about controlling other instances of user clients connected to the same account. Implementing it it in Yaxim could be rather useful because there are many users connected to XMPP from different places simultaneously, e.g. from oridnary PC, from laptop, from work and from mobile phone.

In Yaxim's situation it happens particularly often when it disconnects from XMPP network becaus of GSM network failures.

Example:
You chat w/ someone, network fails for some reason. Your buddy's messages are not lost, they just go to some other resource, for example home or laptop or smth else. When Yaxim connects back you ether don't know if user had sent you something or he continues the conversation from some other place.

So it would be neat!..

**Comment by ge0rg** [comment]
This is something that should be solved by means of Carbons (already implemented for some time) and MAM (tracked in #98). I think there is really no need to implement XEP-0146 in yaxim, so I'm closing this.
