### ISSUE TITLE
feature request: optional support XEP-0118(user tune)

### ISSUE THREAD

**Issue by one-dash** [pfleidi/yaxim#37]
AFAIK there is no XMPP client for Android platform supporting this feature. So iplementing it Yaxim could benefit from that fact, provided that Android platform has player API.

Making this feature optional will help reduce bandwidth and battery usage.

**Comment by ge0rg** [comment]
It looks like this feature is not highly demanded for, and my goal is to keep yaxim slim and light, so I'm not going to implement it in the foreseeable future. Sorry.
