### ISSUE TITLE
Support OTR-encryption

### ISSUE THREAD

**Issue by Dahie** [pfleidi/yaxim#82]
Is it possible in a future release to support OTR-encryption?

**Comment by ge0rg** [comment]
With the advent of OMEMO, there is no more use in implementing OTR. OMEMO is more modern, allows multi-party communication and doesn't suffer from incorrectly implemented client plugins.

**Comment by Urgant** [comment]
OTR is better than OMEMO. OMEMO has two requirements: your server and the server of your contact need to support PEP. The second requirement is mutual presence subscription.
