### ISSUE TITLE
Feature Request, Implement XEP-0016 or XEP-0191 for serverside presence blocking while running in background

### ISSUE THREAD

**Issue by balu-** [pfleidi/yaxim#92]
Please implement eigther XEP-0016 or XEP-0191 and implement a function witch disallows the server to send presence notifications to the mobile client while its running in background.
This way using yaxim could save a lot of battery power cause by the cpu and baseband sleeping and not keept awake by all the presence notifications. See therefore also http://www.deepdarc.com/2008/02/14/mobile-xmpp/

**Comment by ge0rg** [comment]
In the mean time, [XEP-0352: Client State Indication](http://xmpp.org/extensions/xep-0352.html) has been released, that provides a superior method to reduce unwanted traffic. This has been implemented in yaxim via the `google:queue` signalling mechanism in #143.
